name: oohferta
description: OohFerta App.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^5.2.0+1
  flutter_modular: ^5.0.3

  flutter_animate: ^4.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - lib/src/shared/assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/src/shared/assets/fonts/Poppins-Medium.ttf
        - asset: lib/src/shared/assets/fonts/Poppins-Regular.ttf
        - asset: lib/src/shared/assets/fonts/Poppins-Bold.ttf
          weight: 900
        - asset: lib/src/shared/assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/src/shared/assets/fonts/Poppins-Italic.ttf
          style: italic
